const {chromium}=require('../Playwright/node_modules/playwright');
const {pathToFileURL}=require('url');const path=require('path');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[],remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});
 await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);await page.waitForTimeout(200);
 assert(await page.isVisible('#title-screen'));assert.equal(await page.evaluate(()=>menuOpen),true);
 await page.click('#tab-record');assert(await page.isVisible('#log'));await page.click('#tab-play');
 await page.screenshot({path:path.join(__dirname,'title-preview.png')});await page.click('#resume');
 assert.deepEqual(await page.evaluate(()=>[renderer.domElement.clientWidth,renderer.domElement.clientHeight]),[1440,1000]);
 assert.equal(await page.locator('.left,.right,#hand-0,#hand-1').count(),0);console.log('PASS title / settings / records / full-window board without sidebars');
 async function square(i,unit=false){const p=await page.evaluate(({i,unit})=>{let v=position(i);v.y=unit?.65:.12;v.project(camera);let r=renderer.domElement.getBoundingClientRect();return{x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2};},{i,unit});await page.mouse.click(p.x,p.y);}
 await page.evaluate(()=>{window.menuSuppressed=false;document.addEventListener('contextmenu',e=>window.menuSuppressed=e.defaultPrevented);});
 await page.mouse.click(700,450,{button:'right'});assert(await page.evaluate(()=>window.menuSuppressed));assert.equal(await page.evaluate(()=>selection),null);
 const angleBefore=await page.evaluate(()=>angle);await page.mouse.move(700,450);await page.mouse.down({button:'right'});await page.mouse.move(780,490,{steps:5});await page.mouse.up({button:'right'});assert.notEqual(await page.evaluate(()=>angle),angleBefore);assert.equal(await page.evaluate(()=>selection),null);await page.click('#reset-view');console.log('PASS right drag / native context menu suppressed / right click never moves pieces');
 await square(54,true);assert.equal(await page.evaluate(()=>selection.from),54);await square(45);await page.waitForFunction(()=>state.ply===2&&!busy);await page.click('#undo');assert.equal(await page.evaluate(()=>state.ply),0);
 // Pause a pending CPU turn by opening the title screen.
 await page.evaluate(()=>{execute(E.legal(state).find(m=>m.from===54));});await page.waitForFunction(()=>{if(state.ply===1&&!busy){$('menu').click();return true;}return false;});await page.waitForTimeout(900);assert.equal(await page.evaluate(()=>state.ply),1);await page.click('#tab-record');assert.equal(await page.locator('#log li').count(),1);await page.click('#tab-play');await page.click('#resume');await page.waitForFunction(()=>state.ply===2&&!busy);console.log('PASS move / CPU / undo / CPU pauses at title and resumes');
 await page.click('#menu');await page.selectOption('#mode','local');await page.reload();assert(await page.isVisible('#title-screen'));assert.equal(await page.evaluate(()=>state.ply),2);await page.click('#resume');console.log('PASS saved game reopens at title');
 await page.click('#fullscreen');await page.waitForFunction(()=>!!document.fullscreenElement);await page.click('#fullscreen');await page.waitForFunction(()=>!document.fullscreenElement);console.log('PASS enter and leave browser fullscreen');
 await page.evaluate(()=>{epoch++;state=E.initial();state.board.fill(null);state.board[80]={t:'K',s:0,p:false};state.board[0]={t:'K',s:1,p:false};state.board[31]={t:'P',s:0,p:false};state.board[22]={t:'S',s:1,p:true};history=[E.copy(state)];records=[];lastMove=null;ended='';rebuild();renderUI();});
 await square(31,true);await square(22,true);await page.click('#promote-yes');await page.waitForFunction(()=>state.ply===1&&!busy);assert.equal(await page.evaluate(()=>state.hands[0].S),1);assert(await page.evaluate(()=>state.board[22].p));
 await page.evaluate(()=>{state.turn=0;renderUI();});const rp=await page.evaluate(()=>{let v=reserveLayer.children[0].position.clone();v.y+=.25;v.project(camera);let r=renderer.domElement.getBoundingClientRect();return{x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2};});await page.mouse.click(rp.x,rp.y);assert.equal(await page.evaluate(()=>selection?.drop),'S');await square(50);await page.waitForFunction(()=>state.ply===2&&!busy);assert.equal(await page.evaluate(()=>state.board[50].t),'S');console.log('PASS promotion / same-board capture / select 3D tray / redeploy');
 await page.click('#resign');await page.click('#confirm-yes');assert.match(await page.textContent('#turn-status'),/勝利/);await page.click('#menu');await page.click('#restart');await page.click('#confirm-yes');assert.equal(await page.evaluate(()=>state.ply),0);assert(!await page.isVisible('#title-screen'));
 await page.click('#view');await page.click('#reset-view');await page.uncheck('#labels');assert(await page.evaluate(()=>labelSprites.every(s=>!s.visible)));await page.check('#labels');await page.screenshot({path:path.join(__dirname,'screenshot.png')});
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>[renderer.domElement.clientWidth,renderer.domElement.clientHeight]),[390,844]);assert(await page.evaluate(()=>camera.position.length()<scene.fog.near));await page.screenshot({path:path.join(__dirname,'screenshot-mobile.png')});await page.click('#menu');assert(await page.isVisible('#resume'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'title-mobile.png')});
 await page.click('#help');assert(await page.isVisible('#help-dialog'));await page.click('#help-close');
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);console.log('PASS reset / responsive title and board / help / zero errors and zero network');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
