(function(root){
'use strict';
const types=['R','B','G','S','N','L','P'], names={K:'王',R:'飛',B:'角',G:'金',S:'銀',N:'桂',L:'香',P:'歩'}, promoted={R:'龍',B:'馬',S:'成銀',N:'成桂',L:'成香',P:'と'};
const inside=(x,y)=>x>=0&&x<9&&y>=0&&y<9, zone=(s,y)=>s===0?y<=2:y>=6;
function initial(){let s={board:Array(81).fill(null),hands:[{},{}],turn:0,ply:0};for(let side=0;side<2;side++){types.forEach(t=>s.hands[side][t]=0);let back=side===0?8:0,pawn=side===0?6:2;['L','N','S','G','K','G','S','N','L'].forEach((t,x)=>s.board[back*9+x]={t,s:side,p:false});for(let x=0;x<9;x++)s.board[pawn*9+x]={t:'P',s:side,p:false};s.board[(side===0?7:1)*9+(side===0?1:7)]={t:'B',s:side,p:false};s.board[(side===0?7:1)*9+(side===0?7:1)]={t:'R',s:side,p:false};}return s;}
function copy(s){return {board:s.board.map(p=>p?{...p}:null),hands:s.hands.map(h=>({...h})),turn:s.turn,ply:s.ply};}
function targets(s,i,includeFriendly=false){let p=s.board[i];if(!p)return [];let x=i%9,y=Math.floor(i/9),f=p.s===0?-1:1,out=[];let step=(dx,dy,slide=false)=>{for(let n=1;n<=9;n++){let xx=x+dx*n,yy=y+dy*f*n;if(!inside(xx,yy))break;let j=yy*9+xx,q=s.board[j];if(!q||q.s!==p.s||includeFriendly)out.push(j);if(q||!slide)break;}};
let t=p.p&&['P','L','N','S'].includes(p.t)?'G':p.t;
if(t==='P')step(0,1);if(t==='L')step(0,1,true);if(t==='N'){step(-1,2);step(1,2);}if(t==='S')[[-1,1],[0,1],[1,1],[-1,-1],[1,-1]].forEach(d=>step(...d));if(t==='G')[[-1,1],[0,1],[1,1],[-1,0],[1,0],[0,-1]].forEach(d=>step(...d));if(t==='K')for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)if(a||b)step(a,b);
if(t==='R'||t==='B'){let ds=t==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[-1,1],[1,-1],[-1,-1]];ds.forEach(d=>step(...d,true));if(p.p)(t==='B'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[-1,1],[1,-1],[-1,-1]]).forEach(d=>step(...d));}return out;}
function check(s,side){let k=s.board.findIndex(p=>p&&p.s===side&&p.t==='K');if(k<0)return true;return s.board.some((p,i)=>p&&p.s!==side&&targets(s,i).includes(k));}
function apply(s,m){let n=copy(s),side=s.turn;if(m.drop){n.hands[side][m.drop]--;n.board[m.to]={t:m.drop,s:side,p:false};}else{let p=n.board[m.from],q=n.board[m.to];if(q&&q.t!=='K')n.hands[side][q.t]++;n.board[m.to]={...p,p:p.p||!!m.promote};n.board[m.from]=null;}n.turn=1-side;n.ply++;return n;}
function dead(t,side,y){return (t==='P'||t==='L')&&(side===0?y===0:y===8)||t==='N'&&(side===0?y<=1:y>=7);}
function legal(s,skipPawnMate=false){let out=[],side=s.turn;function accept(m){let n=apply(s,m);if(check(n,side))return;if(!skipPawnMate&&m.drop==='P'){let king=n.board.findIndex(p=>p&&p.s!==side&&p.t==='K');let forward=side===0?-9:9;if(m.to+forward===king&&!legal(n,true).length)return;}out.push(m);}
s.board.forEach((p,i)=>{if(!p||p.s!==side)return;targets(s,i).forEach(to=>{if(s.board[to]?.t==='K')return;let y=Math.floor(to/9),can=!p.p&&p.t!=='G'&&p.t!=='K'&&(zone(side,y)||zone(side,Math.floor(i/9)));if(p.p||!dead(p.t,side,y))accept({from:i,to,promote:false});if(can)accept({from:i,to,promote:true});});});
for(let t of types){if(!s.hands[side][t])continue;for(let to=0;to<81;to++){if(s.board[to]||dead(t,side,Math.floor(to/9)))continue;if(t==='P'&&s.board.some((p,i)=>p&&p.s===side&&p.t==='P'&&!p.p&&i%9===to%9))continue;accept({drop:t,to});}}return out;}
const value={K:20000,R:1000,B:850,G:600,S:500,N:350,L:300,P:100};
function evaluate(s,side){let v=0;s.board.forEach((p,i)=>{if(p){let progress=p.s===0?8-Math.floor(i/9):Math.floor(i/9);v+=(p.s===side?1:-1)*(value[p.t]+(p.p?(p.t==='R'||p.t==='B'?220:400):0)+progress*4+(4-Math.abs(i%9-4))*3);}});for(let c=0;c<2;c++)for(let t of types)v+=(c===side?1:-1)*s.hands[c][t]*value[t]*1.08;return v;}
function choose(s,level=1){let moves=legal(s),side=s.turn;if(!moves.length)return null;let ranked=moves.map(m=>{let n=apply(s,m);return {m,n,v:evaluate(n,side)+Math.random()*(level?15:180)};}).sort((a,b)=>b.v-a.v);if(!level)return ranked[0].m;let best=-Infinity,chosen=ranked[0].m;for(let a of ranked.slice(0,16)){let replies=legal(a.n);let worst=Infinity;if(!replies.length)worst=check(a.n,a.n.turn)?100000:0;for(let b of replies)worst=Math.min(worst,evaluate(apply(a.n,b),side));let score=worst+a.v*.03;if(score>best){best=score;chosen=a.m;}}return chosen;}
function key(s){return s.turn+'|'+s.board.map(p=>p?`${p.s}${p.t}${p.p?1:0}`:'.').join('')+'|'+s.hands.map(h=>types.map(t=>h[t]).join(',')).join('|');}
function repetition(history){let last=history.at(-1),matches=[];history.forEach((h,i)=>{if(key(h)===key(last))matches.push(i);});if(matches.length<4)return null;let start=matches.at(-4);for(let side=0;side<2;side++){let turns=history.slice(start+1).filter(h=>h.turn!==side);if(turns.length&&turns.every(h=>check(h,h.turn)))return {loser:side};}return {draw:true};}
const api={initial,copy,targets,check,apply,legal,choose,key,repetition,names,promoted,types,zone};if(typeof module!=='undefined')module.exports=api;root.Shogi=api;
})(typeof window!=='undefined'?window:globalThis);
