'use strict';
const $=id=>document.getElementById(id),E=Shogi;
const lore={P:['足軽','素朴な兜と短槍を携えた、軍の基本部隊。','前へ1マス。成ると金と同じ動き。'],L:['長槍の突撃兵','長い槍を構え、一直線に戦線を突破する。','前方へ何マスでも。駒は飛び越せません。'],N:['騎兵','軍馬にまたがり、味方の頭上を跳び越える。','前へ2マス、左右へ1マスの位置に跳躍。'],S:['銀の隊長','銀鎧と細身の剣を持つ、俊敏な前線指揮官。','前3方向と斜め後ろへ1マス。'],G:['金の武将','黄金の重装鎧をまとい、王の側を守る。','斜め後ろ以外の6方向へ1マス。'],K:['軍の王','王冠と長いマントをまとった、軍の中心。','周囲8方向へ1マス。敵の利きには入れません。'],B:['大鳥の遊撃将','翼を広げた大鳥に乗り、上空から斜めに急襲。','斜めへ何マスでも。成ると縦横1マスも追加。'],R:['戦車将軍','四輪の重戦車を駆り、地上の戦線を切り開く。','縦横へ何マスでも。成ると斜め1マスも追加。']};
let menuOpen=true;
let state=E.initial(),history=[E.copy(state)],records=[],selection=null,available=[],busy=false,ended='',lastMove=null,epoch=0,anim=null,sound=false,ctx=null,toastTimer,topView=false,angle=0,elevation=.94,distance=17.5;
let scene,camera,renderer,units=new Map(),tiles=[],marks=[],sparks=[],raycaster,pointer,unitLayer,labelSprites=[];
const colors=[0xc64f46,0x448fca],lightColors=[0xef8771,0x83c9ef],matCache=new Map(),geoCache=new Map(),labelCache=new Map();
function material(color,metal=0){let key=color+'|'+metal;if(!matCache.has(key))matCache.set(key,new THREE.MeshStandardMaterial({color,metalness:metal,roughness:metal?.42:.8}));matCache.get(key).color.setHex(color).convertSRGBToLinear();return matCache.get(key);}
function geometry(type,args){let key=type+args.join(',');if(!geoCache.has(key))geoCache.set(key,new THREE[type](...args));return geoCache.get(key);}
function mesh(parent,type,args,color,pos=[0,0,0],scale=null,metal=0){let m=new THREE.Mesh(geometry(type,args),material(color,metal));m.position.set(...pos);if(scale)m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
const box=(p,w,h,d,c,x=0,y=0,z=0,metal=0)=>mesh(p,'BoxGeometry',[w,h,d],c,[x,y,z],null,metal);
const ball=(p,r,c,x=0,y=0,z=0,scale=null)=>mesh(p,'SphereGeometry',[r,8,6],c,[x,y,z],scale);
const cyl=(p,r1,r2,h,c,x=0,y=0,z=0,metal=0)=>mesh(p,'CylinderGeometry',[r1,r2,h,10],c,[x,y,z],null,metal);
function limb(p,a,b,r,color){let v1=new THREE.Vector3(...a),v2=new THREE.Vector3(...b);let m=cyl(p,r,r,v1.distanceTo(v2),color);m.position.copy(v1).add(v2).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v2.sub(v1).normalize());return m;}
function label(text,side){let key=text+side;if(!labelCache.has(key)){let c=document.createElement('canvas');c.width=128;c.height=80;let x=c.getContext('2d');x.fillStyle=side===0?'#5b2725':'#1c405a';x.beginPath();x.roundRect(6,7,116,64,14);x.fill();x.strokeStyle=side===0?'#e98b74':'#90c6e9';x.lineWidth=3;x.stroke();x.font='bold 47px "Yu Mincho",serif';x.textAlign='center';x.textBaseline='middle';x.fillStyle='#fff1cd';x.fillText(text,64,43,107);let tex=new THREE.CanvasTexture(c);labelCache.set(key,new THREE.SpriteMaterial({map:tex,depthTest:false,transparent:true}));}let s=new THREE.Sprite(labelCache.get(key));s.scale.set(.4,.25,1);s.renderOrder=5;return s;}
function soldier(parent,p,offset=0,small=false){let g=new THREE.Group();parent.add(g);g.position.y=offset;let c=colors[p.s],armor=p.p?0xe0ba60:p.t==='G'?0xceaa52:p.t==='S'?0xb9c9d4:c;let metal=p.p||['G','S','K'].includes(p.t)?.6:.12;
let legs=[];for(let x of [-.095,.095]){let leg=new THREE.Group();leg.position.set(x,.33,0);g.add(leg);box(leg,.115,.23,.13,0x29323a,0,-.105,0);box(leg,.13,.085,.21,0x333133,0,-.23,-.035);legs.push(leg);}cyl(g,.15,.22,.3,armor,0,.49,0,metal);box(g,.36,.09,.21,armor,0,.6,0,metal);box(g,.22,.08,.24,0x5b4531,0,.36,0);box(g,.065,.065,.025,0xf2d489,0,.36,-.135,.5);
ball(g,.125,0xe0b998,0,.77,0);cyl(g,.153,.17,.085,c,0,.86,0,.2);mesh(g,'SphereGeometry',[.15,8,5,0,Math.PI*2,0,Math.PI/2],armor,[0,.89,0],null,metal);box(g,.18,.033,.085,0x283640,0,.785,-.10);box(g,.09,.045,.025,0xe0b998,0,.725,-.11);
let armL=limb(g,[-.2,.6,0],[-.25,.4,-.05],.055,armor),armR=limb(g,[.2,.6,0],[.26,.48,-.12],.055,armor);ball(g,.055,0xe0b998,.26,.48,-.12);
if(['K','G','S'].includes(p.t)||p.p){let cape=box(g,.31,.43,.045,c,0,.44,.15);cape.rotation.x=-.2;}
if(p.t==='K'){cyl(g,.14,.135,.10,0xe5bc55,0,1.015,0,.7);for(let a=0;a<5;a++){let q=a*Math.PI*2/5;mesh(g,'ConeGeometry',[.035,.12,4],0xf3cc63,[Math.sin(q)*.11,1.09,Math.cos(q)*.11],null,.7);}ball(g,.035,0xe25047,0,1.065,-.137);}
const weapon=new THREE.Group();g.add(weapon);weapon.position.set(.26,.48,-.12);parent.userData.weapon=weapon;
if(p.t==='P'||p.t==='L'){let h=p.t==='L'?1.17:.72;limb(weapon,[.26,.18,-.12],[.26,.18+h,-.18],.018,0x6d492a);mesh(weapon,'ConeGeometry',[.05,.16,4],0xd8e3dc,[.26,.28+h,-.18],null,.7);}else{let blade=box(weapon,.045,.42,.055,0xdbe6e2,.28,.69,-.17,.7);blade.rotation.z=-.22;box(weapon,.17,.045,.07,0xe5bd69,.24,.49,-.17,.5);}
weapon.children.forEach(part=>part.position.sub(weapon.position));
if(p.p){mesh(g,'TorusGeometry',[.18,.018,6,24],0xf5d174,[0,1.15,0]).rotation.x=Math.PI/2;}
if(small)g.scale.setScalar(.72);parent.userData.legs=legs;parent.userData.arms=[armL,armR];parent.userData.rider=g;return g;}
function model(p,index,registerLabel=true){let g=new THREE.Group();g.userData={index,type:p.t,side:p.s};cyl(g,.34,.39,.09,0x26343b,0,.075,0);cyl(g,.345,.345,.035,colors[p.s],0,.13,0,.25);let body=new THREE.Group();g.add(body);body.position.y=.14;body.rotation.y=p.s===0?0:Math.PI;g.userData.body=body;
if(p.t==='N'){ball(body,.23,0x755344,0,.39,0,[.68,.85,1.4]);for(let x of [-.115,.115])for(let z of [-.18,.17])limb(body,[x,.39,z],[x,.08,z-.035],.035,0x604539);limb(body,[0,.43,-.19],[0,.66,-.27],.095,0x805d47);ball(body,.115,0x88654e,0,.68,-.31,[.8,.95,1.5]);for(let x of [-.05,.05])mesh(body,'ConeGeometry',[.035,.13,4],0x6d4b3b,[x,.82,-.28]);box(body,.22,.06,.25,colors[p.s],0,.55,.03);limb(body,[0,.48,.27],[0,.2,.37],.03,0x292d30);soldier(body,p,.43,true);}
else if(p.t==='B'){ball(body,.23,0xe1d6b6,0,.38,0,[.7,.85,1.5]);ball(body,.115,0xf2e5c6,0,.54,-.29);let beak=mesh(body,'ConeGeometry',[.055,.16,4],0xd6a255,[0,.52,-.42]);beak.rotation.x=-Math.PI/2;for(let x of [-.075,.075])ball(body,.023,0x152c35,x,.565,-.34);let wings=[];for(let side of [-1,1]){let w=new THREE.Group();w.position.set(side*.12,.46,0);body.add(w);for(let i=0;i<4;i++){let feather=box(w,.35-i*.03,.05,.105, i%2?0xd9cba5:0xf0e4c7,side*(.18+i*.065),-.025*i,.02+i*.085);feather.rotation.z=side*(.16+i*.04);feather.rotation.y=side*-.15;}w.rotation.z=side*.15;wings.push(w);}body.userData.wings=wings;for(let x of [-.1,.1])limb(body,[x,.3,0],[x,.08,-.04],.023,0xd0a44f);soldier(body,p,.40,true);}
else if(p.t==='R'){box(body,.49,.15,.58,0x65472f,0,.27,0);for(let x of [-.29,.29])for(let z of [-.2,.2]){let wheel=cyl(body,.15,.15,.075,0x29343a,x,.2,z,.35);wheel.rotation.z=Math.PI/2;body.userData.wheels??=[];body.userData.wheels.push(wheel);box(wheel,.20,.082,.026,0xc7b086,0,0,0,.4);box(wheel,.026,.082,.20,0xc7b086,0,0,0,.4);let hub=cyl(body,.065,.065,.085,0xccb075,x,.2,z,.5);hub.rotation.z=Math.PI/2;}box(body,.54,.25,.075,colors[p.s],0,.45,-.26,.3);box(body,.055,.2,.46,colors[p.s],-.25,.43,0,.3);box(body,.055,.2,.46,colors[p.s],.25,.43,0,.3);box(body,.4,.035,.06,0xe0be6a,0,.58,-.26,.5);for(let x of [-.13,.13]){let spike=mesh(body,'ConeGeometry',[.06,.22,5],0xbed0d0,[x,.4,-.39],null,.6);spike.rotation.x=-Math.PI/2;}soldier(body,p,.27,true);limb(body,[.21,.35,.23],[.21,1.1,.23],.015,0xc7ac74);box(body,.24,.18,.025,colors[p.s],.10,1.03,.23);}
else soldier(body,p,0,false);
if(p.p){let ring=mesh(g,'TorusGeometry',[.36,.025,6,32],0xf3cc64,[0,.19,0],null,.6);ring.rotation.x=Math.PI/2;}
let tag=label(p.p?E.promoted[p.t]:E.names[p.t],p.s);tag.position.set(0,1.43,0);tag.visible=$('labels').checked;g.add(tag);if(registerLabel)labelSprites.push(tag);g.position.copy(position(index));return g;}
function position(i){return new THREE.Vector3(i%9-4,0,Math.floor(i/9)-4);}
function init3D(){scene=new THREE.Scene();scene.fog=new THREE.Fog(0x19272e,25,52);camera=new THREE.PerspectiveCamera(37,1,.1,100);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;$('arena').prepend(renderer.domElement);$('loading').remove();scene.add(new THREE.HemisphereLight(0xd9ebff,0x54472d,.7));let sun=new THREE.DirectionalLight(0xffe1ad,1.3);sun.position.set(-6,13,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-7,right:7,top:7,bottom:-7,near:1,far:35});sun.shadow.bias=-.0005;sun.shadow.normalBias=.035;scene.add(sun);let fill=new THREE.DirectionalLight(0x81b9ed,.45);fill.position.set(5,6,-8);scene.add(fill);
box(scene,10.3,.42,10.3,0x47382b,0,-.28,0);box(scene,10.15,.08,10.15,0xbaa074,0,-.035,0);box(scene,9.12,.05,9.12,0x594e38,0,.005,0);
for(let y=0;y<9;y++)for(let x=0;x<9;x++){let t=box(scene,.971,.07,.971,(x+y)%2===0?0xbfa879:0xb39a6d,x-4,.035,y-4);t.userData.index=y*9+x;tiles.push(t);}
for(let x of [-3,3])for(let z of [-3,3])box(scene,.75,.55,.75,0x3c3026,x,-.69,z);
let floor=mesh(scene,'PlaneGeometry',[200,200],0x1b2b32,[0,-1.01,0]);floor.rotation.x=-Math.PI/2;floor.castShadow=false;
for(let n=0;n<9;n++){let tag=label(String(9-n),2);tag.material=tag.material.clone();tag.material.opacity=.62;tag.position.set(n-4,.06,4.78);tag.scale.set(.24,.15,1);scene.add(tag);let row=label('一二三四五六七八九'[n],2);row.position.set(4.79,.06,n-4);row.scale.set(.24,.15,1);scene.add(row);}
for(let side of [0,1]){let z=side===0?5.0:-5.0;for(let x of [-4.8,4.8]){limb(scene,[x,-.1,z],[x,1.25,z],.025,0x978162);box(scene,.45,.65,.025,colors[side],x+.2,.9,z);box(scene,.07,.48,.035,0xe0c383,x+.2,.95,z);}}
unitLayer=new THREE.Group();scene.add(unitLayer);initCapturePresentation();raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();new ResizeObserver(resize).observe($('arena'));setupInput();resize();rebuild();requestAnimationFrame(frame);}
function resize(){if(!renderer)return;let w=$('arena').clientWidth,h=$('arena').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();updateCamera();}
function updateCamera(){let d=distance*1.16*Math.max(1,1.34/camera.aspect);scene.fog.near=d+8;scene.fog.far=d+45;camera.far=Math.max(100,d+60);camera.updateProjectionMatrix();camera.position.set(Math.sin(angle)*Math.cos(elevation)*d,Math.sin(elevation)*d,Math.cos(angle)*Math.cos(elevation)*d);camera.lookAt(0,.05,0);}
function rebuild(){unitLayer.clear();units.clear();labelSprites=[];state.board.forEach((p,i)=>{if(p){let m=model(p,i);units.set(i,m);unitLayer.add(m);}});rebuildReserves();highlight();}
function mark(i,color,solid=false){let m=new THREE.Mesh(geometry('BoxGeometry',[.91,.018,.91]),new THREE.MeshBasicMaterial({color,transparent:true,opacity:solid?.28:.12,depthWrite:false}));m.position.copy(position(i));m.position.y=.089;scene.add(m);marks.push(m);let ring=new THREE.Mesh(geometry('TorusGeometry',[solid?.33:.14,.018,6,32]),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(position(i));ring.position.y=.11;scene.add(ring);marks.push(ring);}
function highlight(){for(let m of marks){scene.remove(m);m.material.dispose();}marks=[];if(lastMove){if(lastMove.from!==undefined)mark(lastMove.from,0xddb35d);mark(lastMove.to,0xddb35d);}if(selection?.from!==undefined)mark(selection.from,0xffdc87,true);let seen=new Set();for(let m of available)if(!seen.has(m.to)){mark(m.to,state.board[m.to]?0xff7867:0x72ecb4,true);seen.add(m.to);}if(E.check(state,state.turn)){let k=state.board.findIndex(p=>p&&p.s===state.turn&&p.t==='K');if(k>=0)mark(k,0xff4848,true);}}
function notify(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
function beep(kind){if(!sound)return;try{ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();let time=ctx.currentTime;let notes=kind==='promote'?[440,554,660,880]:kind==='capture'?[130,90,65]:kind==='check'?[440,330,440]:[240,320];notes.forEach((freq,i)=>{let o=ctx.createOscillator(),g=ctx.createGain();o.type=kind==='capture'?'triangle':'sine';o.frequency.setValueAtTime(freq,time+i*.08);g.gain.setValueAtTime(.0001,time+i*.08);g.gain.exponentialRampToValueAtTime(.09,time+i*.08+.015);g.gain.exponentialRampToValueAtTime(.0001,time+i*.08+.18);o.connect(g).connect(ctx.destination);o.start(time+i*.08);o.stop(time+i*.08+.2);});}catch{}}
function explosion(at,promote=false){for(let i=0;i<22;i++){let m=mesh(scene,'IcosahedronGeometry',[.045,0],promote?0xffd674:i%2?0xe9c28a:0xffffff);m.position.copy(at);m.position.y+=.5;sparks.push({m,v:new THREE.Vector3((Math.random()-.5)*3,Math.random()*2+1,(Math.random()-.5)*3),life:0});}}
let lastTime=0;
function frame(t){let dt=Math.min((t-lastTime)/1000,.05);lastTime=t;for(let [i,g] of units){let b=g.userData.body;if(b.userData.wings)b.userData.wings.forEach((w,k)=>w.rotation.z=(k===0?-1:1)*(.1+Math.sin(t*.003+i)*.07));}
if(anim?.cinematic){tickCapture(anim,t,dt);}else if(anim){let a=anim,u=Math.min(1,(t-a.start)/a.duration),ease=u*u*(3-2*u);a.obj.position.lerpVectors(a.from,a.to,ease);if(a.drop)a.obj.scale.setScalar(.43+.57*ease);let type=a.obj.userData.type,height=type==='B'?1.6:type==='N'?1.1:a.drop?.8:.075;a.obj.position.y=Math.sin(u*Math.PI)*height;if(type!=='B'&&type!=='N')a.obj.userData.body.rotation.z=Math.sin(u*Math.PI*12)*.05*Math.sin(u*Math.PI);if(a.obj.userData.body.userData.legs)a.obj.userData.body.userData.legs.forEach((l,k)=>l.rotation.x=Math.sin(u*Math.PI*12+k*Math.PI)*.55);let movingBody=a.obj.userData.body;movingBody.rotation.y=Math.atan2(-(a.to.x-a.from.x),-(a.to.z-a.from.z));if(type==='L')movingBody.rotation.x=-Math.sin(u*Math.PI)*.42;if(type==='R')movingBody.userData.wheels?.forEach(w=>w.rotation.y=u*Math.PI*8);if(type==='B')movingBody.userData.wings?.forEach((w,k)=>w.rotation.z=(k===0?-1:1)*Math.sin(u*Math.PI*6)*.55);if(a.victim&&u>.55){let strike=Math.sin((u-.55)/.45*Math.PI);movingBody.userData.rider?.rotation.set(-strike*.18,0,strike*(type==='S'?Math.sin(u*35)*.25:.15));movingBody.userData.arms?.forEach(arm=>arm.rotation.x=-strike*1.3);}if(a.victim&&u>.66){let v=(u-.66)/.34;a.victim.scale.setScalar(Math.max(.001,1-v));a.victim.rotation.z=v*1.5;if(!a.hit){a.hit=true;explosion(a.to);beep('capture');}}if(u>=1){anim=null;a.done();}}
for(let i=sparks.length-1;i>=0;i--){let p=sparks[i];p.life+=dt;p.v.y-=dt*3;p.m.position.addScaledVector(p.v,dt);p.m.scale.setScalar(Math.max(0,1-p.life));if(p.life>1){scene.remove(p.m);sparks.splice(i,1);}}renderer.render(scene,camera);requestAnimationFrame(frame);}
function canPlay(){return !menuOpen&&!busy&&!ended&&!( $('mode').value==='cpu'&&state.turn===1);}
function showUnit(p){$('selected-unit').hidden=false;$('unit-name').textContent=(p.p?'昇格 · ':'')+lore[p.t][0];$('movement').textContent=p.p&&['P','L','N','S'].includes(p.t)?'成駒：金将と同じ6方向へ1マス。':lore[p.t][2];}
function selectSquare(i){if(!canPlay())return;let possible=available.filter(m=>m.to===i);if(possible.length){if(possible.length===2)askPromotion(possible);else execute(possible[0]);return;}let p=state.board[i];if(p)showUnit(p);if(p?.s===state.turn){selection={from:i};available=E.legal(state).filter(m=>m.from===i);highlight();renderHands();if(!available.length)notify('この部隊は今、移動できません。');}else{selection=null;available=[];highlight();renderHands();}}
function askPromotion(options){busy=true;let d=$('promotion');d.showModal();let finish=yes=>{d.close();busy=false;execute(options.find(m=>!!m.promote===yes));};$('promote-yes').onclick=()=>finish(true);$('promote-no').onclick=()=>finish(false);d.oncancel=e=>{e.preventDefault();finish(false);};}
function setupInput(){
  let start=null,drag=false;
  $('arena').addEventListener('contextmenu',e=>e.preventDefault());
  renderer.domElement.addEventListener('pointerdown',e=>{
    if(menuOpen||anim?.cinematic||![0,2].includes(e.button))return;
    e.preventDefault();start={x:e.clientX,y:e.clientY,angle,elevation,rotate:e.button===2||e.pointerType==='touch',select:e.button===0};drag=false;
    renderer.domElement.setPointerCapture(e.pointerId);
  });
  renderer.domElement.addEventListener('pointermove',e=>{
    if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;
    if(Math.hypot(dx,dy)>6)drag=true;
    if(drag&&start.rotate){angle=start.angle-dx*.007;elevation=Math.max(.35,Math.min(1.52,start.elevation+dy*.006));updateCamera();}
  });
  renderer.domElement.addEventListener('pointerup',e=>{
    if(!start)return;const click=start.select&&!drag;start=null;if(!click)return;
    const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);
    const reserves=raycaster.intersectObjects(reserveLayer.children,true);
    if(reserves.length){let g=reserves[0].object;while(g.parent&&g.parent!==reserveLayer)g=g.parent;selectReserve(g.userData.drop,g.userData.side);return;}
    const hits=raycaster.intersectObjects(unitLayer.children,true);let index;
    for(const hit of hits){let obj=hit.object;while(obj.parent&&obj.parent!==unitLayer)obj=obj.parent;if(obj.userData.index!==undefined){index=obj.userData.index;break;}}
    if(index===undefined){const hit=raycaster.intersectObjects(tiles)[0];if(hit)index=hit.object.userData.index;}
    if(index!==undefined)selectSquare(index);
  });
  renderer.domElement.addEventListener('pointercancel',()=>{start=null;});
  renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();if(menuOpen||anim?.cinematic)return;distance=Math.max(9,Math.min(26,distance+e.deltaY*.008));updateCamera();},{passive:false});
}
function execute(m){if(busy||ended)return;busy=true;selection=null;available=[];highlight();let before=state,p=m.drop?{t:m.drop,s:state.turn,p:false}:state.board[m.from],victim=units.get(m.to),obj=m.drop?model(p,m.to):units.get(m.from);if(m.drop)unitLayer.add(obj);let target=position(m.to),from=m.drop?reservePosition(state.turn,reserveSlot(state.turn,m.drop)-1):position(m.from);if(m.drop){const departing=reserveLayer.children.filter(g=>g.userData.side===state.turn&&g.userData.drop===m.drop).at(-1);if(departing)departing.visible=false;obj.position.copy(from);obj.scale.setScalar(.43);}let currentEpoch=epoch;beep('move');anim={obj,victim,from,to:target,drop:!!m.drop,start:performance.now(),duration:m.drop?1000:({P:650,L:540,N:800,S:530,G:830,K:880,B:1000,R:850}[p.t]),done:()=>{if(currentEpoch!==epoch)return;state=E.apply(before,m);history.push(E.copy(state));lastMove=m;let rank='一二三四五六七八九'[Math.floor(m.to/9)],name=p.p?E.promoted[p.t]:E.names[p.t];records.push({side:p.s,text:`${9-m.to%9}${rank}${name}${m.drop?'打':m.promote?'成':''}`,detail:victim?'捕獲 → 自軍へ':m.promote?'装備を強化':m.drop?'再出撃':'進軍',move:m});if(m.promote){explosion(target,true);beep('promote');notify('成り！ 部隊の装備と能力が強化されました。');}else if(victim)notify('敵兵を捕獲。自軍の待機部隊に加わりました。');rebuild();busy=false;determineEnd();renderUI();save();scheduleCPU();}};if(victim)startCapture(anim,p,before.board[m.to]);renderUI();}
function determineEnd(){ended='';let repetition=E.repetition(history);if(repetition)ended=repetition.draw?'千日手 · 引き分け':`${repetition.loser===0?'青':'赤'}軍の勝利 · 連続王手の反則`;else if(!E.legal(state).length)ended=`${state.turn===0?'青':'赤'}軍の勝利 · ${E.check(state,state.turn)?'詰み':'合法手なし'}`;if(ended){notify(ended);beep('promote');}else if(E.check(state,state.turn)){notify('王手！ 王を守る一手を指してください。');beep('check');}}
function renderHands(){
  for(const g of reserveLayer.children)g.scale.setScalar(selection?.drop===g.userData.drop&&state.turn===g.userData.side ? .49:.43);
}
function renderUI(){$('menu').disabled=busy;document.querySelectorAll('.camera-tools button,.camera-tools input').forEach(el=>el.disabled=!!anim?.cinematic);$('mode').disabled=busy;let cpu=$('mode').value==='cpu'&&state.turn===1;$('move-count').textContent=`第 ${state.ply+1} 手`;$('turn-dot').style.background=state.turn===0?'var(--red)':'var(--blue)';$('turn-status').textContent=ended||`${state.turn===0?'赤':'青'}軍の手番${E.check(state,state.turn)?' · 王手':''}`;$('turn-hint').textContent=ended?'新しい対局で再出陣できます。':busy?(anim?.cinematic?'一騎打ち！ 捕獲した部隊は自軍の駒台へ。':'部隊が進軍しています…'):cpu?'青軍の将軍が作戦を考えています…':'ユニットを選んで、光るマスへ進軍。';$('undo').disabled=busy||history.length<2;$('resign').disabled=busy||!!ended;$('level').disabled=$('mode').value!=='cpu';renderHands();let log=$('log');log.replaceChildren();if(!records.length)log.innerHTML='<li class="empty">両軍、配置につく。<br>最初の一手を指しましょう。</li>';records.slice().reverse().forEach((r,j)=>{let li=document.createElement('li');li.innerHTML=`<em>${records.length-j}</em><span class="${r.side===0?'red':'blue'}-text">${r.side===0?'▲':'△'} ${r.text}</span><small>${r.detail}</small>`;log.append(li);});}
function scheduleCPU(){if(menuOpen||ended||busy||$('mode').value!=='cpu'||state.turn!==1)return;let token=epoch;setTimeout(()=>{if(menuOpen||token!==epoch||busy||ended||$('mode').value!=='cpu'||state.turn!==1)return;if(document.querySelector('dialog[open]')){scheduleCPU();return;}let m=E.choose(state,Number($('level').value));if(m)execute(m);},400);}
function save(){try{localStorage.setItem('gunki-save-v1',JSON.stringify({history,records,ended,mode:$('mode').value,level:$('level').value}));}catch{}}
function load(){try{let data=JSON.parse(localStorage.getItem('gunki-save-v1'));if(!data||!Array.isArray(data.history)||!data.history.length||data.history.length>2000)return;if(!data.history.every(s=>s.board?.length===81&&s.hands?.length===2&&[0,1].includes(s.turn)))return;history=data.history;state=E.copy(history.at(-1));records=data.records||[];lastMove=records.at(-1)?.move||null;ended=data.ended||'';$('mode').value=data.mode==='local'?'local':'cpu';$('level').value=data.level==='0'?'0':'1';}catch{state=E.initial();history=[E.copy(state)];records=[];}}
function confirmAction(title,text,action){$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm').showModal();$('confirm-yes').onclick=()=>{$('confirm').close();action();};$('confirm-no').onclick=()=>$('confirm').close();}
function newGame(){epoch++;cleanupCapture();if(anim){unitLayer.remove(anim.obj);anim=null;}busy=false;state=E.initial();history=[E.copy(state)];records=[];selection=null;available=[];lastMove=null;ended='';$('selected-unit').hidden=true;$('unit-name').textContent='';$('movement').textContent='';rebuild();renderUI();save();notify('両軍、配置完了。赤軍から出陣です。');}
$('restart').onclick=()=>{if(history.length>1||busy)confirmAction('新しい対局を始めますか？','現在の対局を終了し、初期配置に戻します。',newGame);else newGame();};
$('mode').onchange=()=>{epoch++;renderUI();save();scheduleCPU();};$('level').onchange=save;
$('undo').onclick=()=>{if(busy||history.length<2)return;epoch++;history.pop();records.pop();if($('mode').value==='cpu'&&history.at(-1).turn===1&&history.length>1){history.pop();records.pop();}state=E.copy(history.at(-1));ended='';selection=null;available=[];lastMove=records.at(-1)?.move||null;rebuild();renderUI();save();notify('一手前の作戦に戻りました。');scheduleCPU();};
$('resign').onclick=()=>confirmAction('投了しますか？',`${state.turn===0?'赤':'青'}軍が投了し、対局を終了します。`,()=>{epoch++;ended=`${state.turn===0?'青':'赤'}軍の勝利 · 投了`;selection=null;available=[];highlight();renderUI();save();notify(ended);});
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'音 ON':'音 OFF';$('sound').setAttribute('aria-pressed',sound);if(sound)beep('move');};$('help').onclick=()=>$('help-dialog').showModal();$('help-close').onclick=()=>$('help-dialog').close();
$('view').onclick=()=>{topView=!topView;elevation=topView?1.51:.94;$('view').textContent=topView?'立体':'俯瞰';updateCamera();};$('rotate-left').onclick=()=>{angle-=Math.PI/4;updateCamera();};$('rotate-right').onclick=()=>{angle+=Math.PI/4;updateCamera();};$('reset-view').onclick=()=>{angle=0;elevation=.94;distance=17.5;topView=false;$('view').textContent='俯瞰';updateCamera();};$('labels').onchange=()=>labelSprites.forEach(s=>s.visible=$('labels').checked);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){selection=null;available=[];$('selected-unit').hidden=true;highlight();renderHands();}});
load();try{init3D();renderUI();scheduleCPU();}catch(e){console.error(e);$('loading')?.remove();let p=document.createElement('p');p.style.cssText='padding:80px 30px;color:#efc887;line-height:2';p.textContent='3D画面を起動できませんでした。Chrome または Edge で開き、ブラウザのグラフィック アクセラレーションを有効にしてください。';$('arena').append(p);}

